name: "openweather_dbt"
version: "1.0"
config-version: 2

profile: "openweather"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  openweather_dbt:
    staging:
      +schema: staging
      +materialized: view
    mart:
      +schema: mart
      +materialized: table
